version: '3'

services:
  engine:
    restart: always
    build:
      context: ../
      dockerfile: ./Dockerfile
    environment:
      - NATS_URL=127.0.0.1
      - NATS_USERNAME=""
      - NATS_PASSWORD=""
      - DB_HOST=127.0.0.1
      - DB_USERNAME=""
      - DB_PASSWORD=""
      - DB_LOCATION=""
      - SECRET=123456
      - MANAGER_PORT=8081
      - PROXY_PORT=8080
      - GATEWAY_PORT=8443
    network_mode: "host"
