version: '3'

services:

  engine:
    restart: always
    image: scyna/engine:0.1.23
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8443:8443"
    environment:
      - NATS_URL=localhost
      - NATS_USERNAME=""
      - NATS_PASSWORD=""
      - DB_HOST=localhost
      - DB_USERNAME=""
      - DB_PASSWORD=""
      - DB_LOCATION=""
      - SECRET=123456
      - MANAGER_PORT=8081
      - PROXY_PORT=8080
      - GATEWAY_PORT=8443
    network_mode: "host"
